# Login 
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "ilaria@polito.it",
  "password": "Ilaria00!"
}

###

# Verifica sessione corrente
GET http://localhost:3001/api/sessions/current

###

# Logout
DELETE http://localhost:3001/api/sessions/current

###

# Ottieni 3 carte iniziali random 
GET http://localhost:3001/api/game/init-cards

###

# Crea nuova partita 
POST http://localhost:3001/api/game
content-type: application/json

{}

###

# Salva le carte iniziali per una partita
POST http://localhost:3001/api/game/1/init-cards
content-type: application/json

{
  "card_ids": [3, 7, 12]
}

###

# Ottieni le carte iniziali della partita 
GET http://localhost:3001/api/game/1/init-cards

###

# Ottieni una situazione da indovinare per la partita 
GET http://localhost:3001/api/game/1/situation

###

# Aggiungi un nuovo round alla partita 
POST http://localhost:3001/api/game/1/round
content-type: application/json

{
  "card_id": 7,
  "round_number": 2
}

###

# Aggiorna esito del round 
PUT http://localhost:3001/api/game/round/1
content-type: application/json

{
  "guessed_correctly": 1,
  "chosen_position": 2
}

###

# Ottieni tutte le carte vinte in una partita 
GET http://localhost:3001/api/game/1/won-cards

###

# Ottieni storico delle partite dell'utente autenticato
GET http://localhost:3001/api/game/user/1

###

# Ottieni cronologia dettagliata di una partita 
GET http://localhost:3001/api/game/1/history

###

# Aggiorna stato partita 
PUT http://localhost:3001/api/game/1/status
content-type: application/json

{
  "status": "win"
}

###

# Ottieni i dati di una singola partita 
GET http://localhost:3001/api/game/1

###

# Partita demo
GET http://localhost:3001/api/demo

###



